name: Build & Test

on:
  push # TODO: fix this for pushes and PRs

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.0, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
